POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Hello World, Hello Universe",
  "important": true,
  "userId": "6a0665bc909fe9960521282e"
}

### Delete note with id 2.
DELETE http://localhost:3001/api/notes/2
Accept: application/json

### Return the landing page.
GET http://localhost:3001/
Accept: text/html

### Return note with id 2.
GET http://localhost:3001/api/notes/6a02b1cf2fb3e77587463c93
Accept: application/json

### Return all notes.
GET http://localhost:3001/api/notes
Accept: application/json

### Add a user.
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "nienie",
  "name": "Nienie",
  "password": "coolbeansbro"
}

