DELETE localhost:3001/api/persons/2
Accept: application/json

### Post new person.
POST localhost:3001/api/persons/
content-type: application/json

{
    "name": "Bobby Yodel",
    "number": "071-23456357"
}

### Post with empty data.
POST localhost:3001/api/persons/
content-type: application/json

{
  "name": "",
  "number": "071-23456357"
}
